server:
  port: 9191

spring:
  application:
    name: payment-processor
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  liquibase:
    change-log: db/changelog/changelog-master.xml

logging:
  level:
    root: info
