server:
  port: 9191

spring:
  application:
    name: payment-processor

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payment-processor-microservice-group-id
      enable-auto-commit-config: true
      trusted-packages: paymentprocessor.dto
      value-default-type: paymentprocessor.dto.PaymentDto
      type-mappings: paymentservice.dto.PaymentDto:paymentprocessor.dto.PaymentDto
    producer:
      acks-config: 1
      retries-config: 5
      delivery-timeout-ms-config: 120000
      max-request-size-config: 10685765
      request-timeout-ms-config: 30000

logging:
  level:
    root: info

topics:
  payment-created:
    name: payment-created
    partitions: 3
    replication: 1
  payment-processed:
    name: payment-processed
    partitions: 3
    replication: 1
  retry-topic:
    name: retry-topic
    partitions: 3
    replication: 1